### ISSUE TITLE
Spawn issue

### ISSUE THREAD

**Issue by jkent** [jkent/tremulous-tremball#4]
Sometimes, players can spawn as the bot.  It is unknown at this time why.

**Comment by jcw9967** [comment]
I feel it's got to do with the clientnum that the client is given when connecting. There could be a conflict with the bot's and the client's clientnum

**Comment by jkent** [comment]
There is another, possibly related bug.  I've seen the bot follow and stick to a client before.  Perhaps attack behavior?

**Comment by jcw9967** [comment]
http://puu.sh/3K75U.png
I did some testing this morning, and both clients seem to connect with slot 0. Seems odd, as though the client numbers aren't being parsed properly or something along those lines.

**Comment by jkent** [comment]
Closed issue due to inactivity.  There are no future plans to work on this.
